Documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

Github-files:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

Tests:
  - changed-files:
      - any-glob-to-any-file: 'src/tests/**'

Core:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/iot_inspector/**/*.py'
          - 'pyproject.toml'
          - 'setup.py'
          - 'uv.lock'

Scripts:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.sh'
          - '**/*.ps1'
          - '**/*.bat'

Data:
  - changed-files:
      - any-glob-to-any-file: 'src/iot_inspector/data/**'

Streamlit:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/iot_inspector/.streamlit/**'
          - '.streamlit/**'