name: Publish Wheel package to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      v-version: ${{ steps.version.outputs.v-version }}
    steps:
      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          release_branch: master
          use_api: true
          increment: major

  build:
    runs-on: ubuntu-latest
    needs: [create_release]
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Create wheel file
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools wheel build setuptools_scm
        PRETEND_VERSION=${{ needs.create_release.outputs.v-version }} python3 -m build --wheel .

    - name: Store the IoT Inspector Python wheel
      uses: actions/upload-artifact@v4
      with:
        name: iot-inspector
        path: dist/*.whl
        if-no-files-found: error

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    if: github.repository == 'nyu-mlab/iot-inspector-client'
    needs: [create_release, build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/iot-inspector  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
      contents: write  # Required for creating releases

    steps:
      - name: Download all the wheel file
        uses: actions/download-artifact@v4
        with:
          name: iot-inspector
          path: dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

      - name: Upload wheel and debian packages to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create_release.outputs.v-version }}
          files: |
            dist/*.whl
